### ISSUE TITLE
实现 OneBot 扩展事件

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/php-libonebot#10]
### 描述

为了提供实现者实现 OneBot 扩展事件的方法，应当提供一个基于四大事件类型的扩展事件抽象类，实现者可以继承此抽象类并实现自己的扩展事件，此抽象类应当要求实现者传入（或配置）实现名称并自动添加前缀。

为了方便实现者进行测试或进行简单的实现，应当同时提供默认的扩展事件类，允许实现者直接使用该类实现扩展事件。为避免实现者滥用，应当在代码中加以限制，仅允许在有限范围内使用。文档中应额外说明推荐用户自行继承抽象类以实现扩展事件。

为避免实现者直接从 `NoticeEvent` 继承，应当在 phpdoc 中写入 `@internal`。

### 例子

```php
// 扩展事件抽象类
abstract class ExtendedNoticeEvent extends NoticeEvent {}

// 实现者定义的扩展事件类
class UserDefinedNoticeEvent extends ExtendedNoticeEvent {}

// 默认的扩展事件类
class DefaultExtendedNoticeEvent extends ExtendedNoticeEvent {}
```

**Comment by sunxyw** [comment]
> 为实现扩展事件（Extended Event），而扩展事件的前缀是由 impl 来决定的，所以 libob 内部是否需要提供一个自动加前缀的抽象扩展事件类呢？

同意，这可以方便实现者实现扩展事件，也可以方便 LibOB 进行处理。

<br>

> 此外扩展事件本身会增加很多字段，理论上确实假定 ExtendedNoticeEvent 应该是 abstract class，扩展的事件额外参数由用户定义。

但这样的话似乎难以满足单文件实现的需求，还是说我们仅对单文件模式提供有限支持，部分进阶功能在单文件中不可用？需要实现者构建目录结构？

**Comment by crazywhalecc** [comment]
还有一种曲线救国的方案，就是提供一个生成 ExtendedEvent 对象的生成器，但我相信这会是一个巨型陨石坑。

倒是完全可以只封装一个简单的生成器，不需要引入巨量的环境，因为其实也没有理由用到生成器的所有能力，就是提供一个最简单基础的模版。

关于单文件实现的需求，问题应该不属于上面提到的是否抽象 NoticeEvent 类了，因为仔细想了下无论如何，总会实现 Action，而 Action 一旦实现就无法通过单文件来操作。

单文件其实是一个面向过程实现的问题，理论上说如果要实现单文件，也可以提供一个 DefaultNoticeEvent extends NoticeEvent，是 final 级别的，只允许缺省情况使用，但一般在文档中推荐使用继承类。

**Comment by sunxyw** [comment]
是否可能增加一个 `ExtendedEvent` 类，其包含标准事件和额外数据，在处理时再序列化成完整的扩展事件？
如：
```php
class ExtendedEvent {
    private $base_event;
    
    private $extended_data;
    
    public function __construct(OneBotEvent $base_event, array $extended_data);

    public function jsonSerialize()
    {
        return array_merge($base_event->jsonSerialize(), $extended_data);
    }
}

**Comment by crazywhalecc** [comment]
> 是否可能增加一个 `ExtendedEvent` 类，其包含标准事件和额外数据，在处理时再序列化成完整的扩展事件？ 如：
> 
> ```
> class ExtendedEvent {
>     private $base_event;
>     
>     private $extended_data;
>     
>     public function __construct(OneBotEvent $base_event, array $extended_data);
> 
>     public function jsonSerialize()
>     {
>         return array_merge($base_event->jsonSerialize(), $extended_data);
>     }
> }
> ```

但这样做的话，不能保证对象直接序列化后扩展字段与原字段平级了呀，所以应该理论上是继承的关系。

**Comment by sunxyw** [comment]
请见测试代码：
```php
class ExtendedEvent implements JsonSerializable
{
    private $base_event;

    private $extended_data;

    public function __construct(OneBotEvent $base_event, array $extended_data)
    {
        $this->base_event = $base_event;
        $this->extended_data = $extended_data;
    }

    public function jsonSerialize(): array
    {
        return array_merge($this->base_event->jsonSerialize(), $this->extended_data);
    }
}

$ob = new \OneBot\V12\OneBot('repl', 'qq', 'REPL-1');
$base_event = new \OneBot\V12\Object\Event\Message\PrivateMessageEvent('USERID', '你好');
$extended_data = [
    'qq.raw_event_id' => 'ABCDEFG',
    'qq.anonymous' => [
        'name' => '匿名者',
        'id' => '1234567'
    ]
];
$extended_event = new ExtendedEvent($base_event, $extended_data);
print_r(json_encode($extended_event));
```

另外 `OneBotEvent` 中需要作出以下修改才能正确进行序列化：
```diff
public function jsonSerialize(): array
{
-    return $this;
+    return (array)$this;
}
```


运行后输出：
```json
{
    "message": {
        "type": "text",
        "data": {
            "text": "\u4f60\u597d"
        }
    },
    "alt_message": null,
    "id": "af6312b3-a6dc-45d1-b288-179c9af4d2ee",
    "impl": "repl",
    "platform": "qq",
    "self_id": "REPL-1",
    "time": 1637476211,
    "type": "message",
    "detail_type": "private",
    "sub_type": "",
    "user_id": "USERID",
    "message_id": null,
    "qq.raw_event_id": "ABCDEFG",
    "qq.anonymous": {
        "name": "\u533f\u540d\u8005",
        "id": "1234567"
    }
}

```

可见扩展字段与原字段是平级的。

**Comment by crazywhalecc** [comment]
实现者自行添加前缀吗？

**Comment by sunxyw** [comment]
> 实现者自行添加前缀吗？

可以在 `ExtendedEvent` 中自动读取 `implement_name` 自动添加前缀。

**Comment by crazywhalecc** [comment]
不继承的话，要怎么 call 到事件触发呢？虽然现在事件触发还没写完，但理论上应该在事件触发的入口处，应该做类型限制，比如 `function emitEvent(OneBotEvent $e)`，而 `ExtendedEvent` 不符合继承条件。

**Comment by sunxyw** [comment]
> 不继承的话，要怎么 call 到事件触发呢？虽然现在事件触发还没写完，但理论上应该在事件触发的入口处，应该做类型限制，比如 `function emitEvent(OneBotEvent $e)`，而 `ExtendedEvent` 不符合继承条件。

PHP 7.2 下不支持Union Type，那么适配类型限制的确有点难。
也许只能让 `ExtendedEvent` 继承 `OneBotEvent`，再让实现者传入 `extended_data`。
如果采用继承方式的话，`ExtendedEvent` 应该为 `abstract` 还是普通类呢，如果是普通类的话，似乎难以根据类名识别事件。
还是说我们仅在 phpdoc 中指定接受的参数类型，再在具体实现中进行判断？

**Comment by crazywhalecc** [comment]
有一种方案不知可不可行：

`abstract class ExtendedNoticeEvent extends NoticeEvent`，这是对应标准中的扩展事件只允许在四大类下进行限制。

`class UserDefinedNoticeEvent extends ExtendedNoticeEvent`，假设这是用户定义的扩展事件。

`class DefaultExtendedNoticeEvent extends ExtendedNoticeEvent`，默认的扩展事件对象，定位类似 stdClass？不过我的想法就是这个只允许有限范围内使用，比如使用其做一些合规测试或只需要一处使用的偏僻事件。文档中额外说明推荐用户自行创建类 `extends` 到 `ExtendedXXXEvent` 。

**Comment by sunxyw** [comment]
同意。

**Comment by crazywhalecc** [comment]
另外为了避免实现者直接从 `NoticeEvent` 这层事件直接继承，可以给 class 加一个 `@internal`。
