### ISSUE TITLE
实现 HTTP 和 WebSocket 客户端

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/php-libonebot#11]
### 描述

解决 OneBot 实现的 `http_hook` 和 `ws_reverse` 通信方式需要 LibOneBot 以客户端 + 事件循环方式启动。经讨论认为应当将 Swoole / Workerman 提供的相关客户端进行封装以使其符合 [PSR-18](https://learnku.com/docs/psr/PSR-18-http-client/2507) 规范。

**Comment by sunxyw** [comment]
> HTTP / WS 客户端是否需要异步处理？

理想情况下支持异步处理自然最好，但考虑到实现难度，也许可以作保留。

<br>

> 客户端是否应该独立编写一个组件库或提供抽象接口（因为考虑到实现者在完成平台协议大概率还是会用到各种通信协议在内）？

HTTP 客户端可以考虑 [PSR-18](https://learnku.com/docs/psr/PSR-18-http-client/2507)，基于此接口完成开发，再由实现者自由选择使用的 HTTP 客户端。
WS 客户端似乎暂无统一的规范，也许需要自行编写或引入第三方库。

<br>

> 引入外部组件编写还是手搓 driver？

😖

**Comment by crazywhalecc** [comment]
WebSocket 客户端在 Swoole / Workerman 环境下都有对应的客户端，我在另一个项目中已经封装好过 WS 异步客户端相关的代码，可以规范化后引入对接 Driver 模式。

HTTP 客户端理论上也可以手搓，因为我们需要对对应的驱动进行兼容，所以对 libob 而言，根据 PSR-18 开发兼容层是必须要做的事情，而底层协议应该放在 Driver 中一并转换或实现。

**Comment by crazywhalecc** [comment]
此外，异步模式似乎是可以板上钉钉的，而且对于 Swoole 本身，可以直接将现有事件加入 Swoole 的事件驱动，而 Workerman 可能适配纯异步会比较困难，但在 Server 模式下只需引入 client 组件就可以。

**Comment by sunxyw** [comment]
同意。
