### ISSUE TITLE
使用 Angular Commit 规范的提议

### ISSUE THREAD

**Issue by sunxyw** [botuniverse/php-libonebot#13]
### 描述

[Angular Commit 规范](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format) 是在前端项目较为通行的 Git 提交规范，且有着庞大的社区支持。
除了有效帮助快速过滤信息外，也可以借助工具基于 Commit Log 自动生成 Changelog。
项目是否有需要使用此规范？

**Comment by crazywhalecc** [comment]
目前工作流和项目代码量还处于最初期的阶段，提前确定标准化流程可以提高效率。

但是感觉 Angular Commit 规范可能更适合大型项目，本项目我更倾向于按照现行的新分支合并流程进行规范，在进行小计划的分支合并时可以做 Summary，或者在发布新版本时对版本间变化做 Summary。
