### ISSUE TITLE
LogLevel 枚举有错误

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/php-libonebot#24]
### 受影响版本

0.3.0

### 描述

在 `Psr\Log\LogLevel` 中，`LogLevel::INFO` 获取到的是字符串 `info`，而在 libob 内，应该让 `ConsoleLogger::$logLevel` 为数字，目前因为这个问题无法正确使用 logger。

### 复现步骤

使用 demo.php，无法显示 info log。

### 解决方案

修改 ConsoleLogger。（具体我也不知道 Psr 的要求是什么，我也去看看。

### 附加信息

![image](https://user-images.githubusercontent.com/20330940/147585533-d330afb8-517d-473a-a978-fa22097ea191.png)
![image](https://user-images.githubusercontent.com/20330940/147585545-34f50a59-38df-4a67-b681-d372e5943723.png)

**Comment by sunxyw** [comment]
`ConsoleLogger` 本身并无问题，在 `demo.php` 内使用 `$ob->getLogger()->info('foo bar');` 可以正常输出 INFO 日志。
![圖片](https://user-images.githubusercontent.com/31698606/147635440-d6bc91f2-3682-49ed-ab8a-06827228fa01.png)

下方的 Workerman 日志由 Workerman 自身输出，见源码：
[displayUI方法](https://github.com/walkor/workerman/blob/master/Worker.php#L757) 及
[safeEcho方法](https://github.com/walkor/workerman/blob/master/Worker.php#L2115)

粗略来看，似乎无法从外部干预，是否有办法截获 / 修改 Workerman 的输出流？

**Comment by crazywhalecc** [comment]
https://github.com/botuniverse/php-libonebot/blob/95e47b32a4509c7d2f9a207b955bbc541a451350/src/OneBot/Logger/Console/ConsoleLogger.php#L130

在这个位置使用了运算符比较级别大小，但是此处的 `$logLevel` 可追溯到前面是字符串 `info`，应该是这里出现了问题，与 Workerman 无关。

Workerman 的输出先留在那，后面我会去掉并自定义格式化（因为 Swoole 那边啥输出也没有）。

**Comment by crazywhalecc** [comment]
Workerman 按 Ctrl+C 的那个提示确实不好弄，不过 Workerman 应该都能重写。
