### ISSUE TITLE
使用 JSON Schema 进行配置验证及提供自动补全

### ISSUE THREAD

**Issue by sunxyw** [botuniverse/php-libonebot#37]
### 描述

目前使用的是内置的数据验证对用户提供的配置文件进行验证，但相关验证规则与代码结合，不易于分别维护，且用户建立、修改配置文件时也无法得到完善的自动补全功能。
建议改用的 JSON Schema 可以在单独文件、甚至外部服务器上存储，能够方便地进行单独维护、更新，而且部分编辑器（IDE）可以根据 JSON Schema 进行自动补全。

**Comment by crazywhalecc** [comment]
目前除了配置文件有哪些地方还需要验证呢

**Comment by sunxyw** [comment]
> 目前除了配置文件有哪些地方还需要验证呢

并没有，只有配置文件需要进行验证，事实上不进行验证任其出错退出也可以，但可能会出现预料外的行为。

**Comment by crazywhalecc** [comment]
现在的代码内对 OB 配置文件的验证是 `hassankhan/config`，那改为 JSON Schema 后是要替换为 `justinrainbow/json-schema` 然后统一抽象个接口吗？

**Comment by sunxyw** [comment]
> 

hassankhan/config 只是对配置文件进行了处理，提供统一的访问接口，本身并没有验证功能，验证功能是通过 lezhnev74/pasvl 实现的，且验证本身和配置管理并无关联。

**Comment by crazywhalecc** [comment]
> > 
> 
> hassankhan/config 只是对配置文件进行了处理，提供统一的访问接口，本身并没有验证功能，验证功能是通过 lezhnev74/pasvl 实现的，且验证本身和配置管理并无关联。

那 JSON Schema 是不是从理论上可以替代这两者呢？

**Comment by sunxyw** [comment]
JSON Schema 的主要作用是验证 JSON 数据的结构，这个跟现在所用的 lezhnev74/pasvl 都是类似于验证器的作用。
而 hassankhan/config 是一个配置管理库，支持使用多种不同类型的配置文件，以及多配置文件，并提供一个简单的接口来进行操作。
总括而言，在其他地方不需要验证器的时候，可以使用 JSON Schema 来替代 PASVL，否则使用 PASVL 或者其他验证器会比较好。

PS: 看了一下 justinrainbow/json-schema 的官方用例，验证的时候入参是数组/对象，那么理论上其也可以对其他格式的配置文件进行验证。

**Comment by crazywhalecc** [comment]
JSON Schema 在 libob 中的使用场景是什么呢？是在收到 Action 请求的时候做校验吗

**Comment by sunxyw** [comment]
> 



> JSON Schema 在 libob 中的使用场景是什么呢？是在收到 Action 请求的时候做校验吗

理论上可以验证任何数据。
但仔细想了想，JSON Schema 的写法相较传统验证器似乎更为繁复，好像又没有必要的样子。

**Comment by crazywhalecc** [comment]
> 理论上可以验证任何数据。 但仔细想了想，JSON Schema 的写法相较传统验证器似乎更为繁复，好像又没有必要的样子。

libob 库本身进行配置校验可以不引入或依旧是推荐引入？JSON Schema 这么说应该是更偏向于使用 libob 来开发 OneBot 实现的人使用的。
