### ISSUE TITLE
ConnectionPool 在 Workerman 下可以使用 SplQueue

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/php-libonebot#38]
### 描述

这样不用 Swoole 的情况下也可以使用 SQLite 组件。

**Comment by sunxyw** [comment]
搜集了点资料，Workerman 下使用数据库单例似乎性能会比较好，每个 Worker 单独一个数据库链接，那在 Workerman 场景下使用单例，Swoole 下使用连接池是否可行呢？可以统一封装成 `getInstance()` 方法？

不是很懂 SplQueue 应该怎么用，是把 SplQueue 对象放到全局变量里吗？

**Comment by crazywhalecc** [comment]
SplQueue 就是一个内部实现的队列，应该比数组要快一些。SplQueue 扔个全局对象就好了。

如果 Workerman 不用考虑异步、协程的问题的话，那就不用也好（代码结构更简单了）。

**Comment by crazywhalecc** [comment]
另外我看目前抽象的是 AbstractObjectPool，是属于对象池，而不是连接池，但是对象池的话在 Workerman 环境下无法使用 Swoole 将不能使用。

**Comment by sunxyw** [comment]
> 另外我看目前抽象的是 AbstractObjectPool，是属于对象池，而不是连接池，但是对象池的话在 Workerman 环境下无法使用 Swoole 将不能使用。

在 Workerman 环境下可以使用全局变量加 SplQueue 的方式实现。但如何分别在 Swoole 和 Workerman 下使用 Channel 和 SplQueue 是一个问题，如果单纯判断的话可能会有点难看。

**Comment by crazywhalecc** [comment]
这个单纯判断应该是不可避免了，因为在 Workerman 和 Swoole 的 Driver 驱动统一接口时就需要至少保留一个驱动使用的类型。

**Comment by crazywhalecc** [comment]
> 这个单纯判断应该是不可避免了，因为在 Workerman 和 Swoole 的 Driver 驱动统一接口时就需要至少保留一个驱动使用的类型。

关于此处，就引伸出了另一个问题：Driver 是不是应该和 OneBot 对象一样，只允许单例运行才行？否则如果开了多个 Driver 可能会遇到不可预估的问题。
