### ISSUE TITLE
新配置文件下 Driver 的相关参数需要尽快反映到文档中，要不然以后就容易忘掉

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/php-libonebot#47]
### 描述

如今使用了 `driver.config.xxx` 方式允许对驱动进行配置，那么也应该尽快完善到文档，我现在已经不知道有哪些参数可以配置了。

**Comment by sunxyw** [comment]
目前内部实现上是将第二个参数直接传入驱动的构造函数里，不经过任何处理。

后续计划支持更多参数，顺序传入构造函数。
