### ISSUE TITLE
通信方式名称类型的选择

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/php-libonebot#49]
### 描述

目前我们的通信方式有四种，但是四种通信方式的 `type` 目前好像还是有定义问题，且标准内也未提到。

- HTTP：`http`
- HTTP WebHook：`webhook` 还是 `http_webhook`？
- WebSocket：`ws` 还是 `websocket`？
- 反向 WebSocket：`ws_reverse` 还是 `websocket_reverse`？

**Comment by sunxyw** [comment]
我个人倾向于 `http` `webhook` `websocket` `websocket_reverse`

但是，为什么不都要呢。毕竟，_小孩子才做选择_
我觉得接受常用的名称作为别名也是一种可行的方法。
