### ISSUE TITLE
请问这个可以支持thinkphp或laravel框架的适配吗？

### ISSUE THREAD

**Issue by asmydream** [botuniverse/php-libonebot#75]
### 描述

如图，想在框架中引入onebot 能给个例子或者教程吗？

**Comment by sunxyw** [comment]
你好~
目前 PHP LibOneBot 仍然处于积极开发阶段，并不适合在生产环境使用。
如果想在 TP 或 Laravel 等框架中集成 PHPLibOB，可以通过命令行等形式来运行。
以 Laravel 为例，可以通过使用 Artisan Console 中定义命令来运行 OneBot 客户端。
_以下代码基于[当前 Master 分支](https://github.com/botuniverse/php-libonebot/tree/e0a374b675798ca84221eba864532eda908847fd)，日后的使用方式可能存在变化。_

```php
<?php
 
namespace App\Console\Commands;
 
use Illuminate\Console\Command;
 
class RunOneBot extends Command
{
    protected $signature = 'onebot:run';
 
    protected $description = 'Run OneBot client';
 
    public function handle()
    {
        $ob = new \OneBot\V12\OneBot('repl', 'qq', 'REPL-1');
        $ob->setLogger(new \OneBot\Logger\Console\ConsoleLogger());
        $ob->setDriver(
            new \OneBot\Driver\Workerman\WorkermanDriver(), 
            new \OneBot\V12\Config\Config('demo.json')
        );
        $ob->setActionHandlerClass(\OneBot\V12\Action\ReplAction::class);
        $ob->run();
    }
}
```
然后就可以通过 `php artisan onebot:run` 运行 OneBot 客户端，并在事件处理中使用 Laravel 相关的功能。

再次重提，我们目前仍处于开发阶段，不保证可以正常使用。
在正式版发布后，我们会考虑撰写相关的集成教程。
